name: Build & Deploy Docs

# Run on pushes to main (for build & deploy) and on PRs (for build only)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Grant only what we need
permissions:
  contents: read      # for checkout
  pages: write        # to push to gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # full history, needed for gh-pages action

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install sphinx sphinx-rtd-theme

      - name: Generate API stubs
        run: |
          sphinx-apidoc \
            --module-first \
            --separate \
            --output-dir docs/api \
            src/video_processing_toolkit

      - name: Build HTML documentation
        working-directory: docs
        run: make html

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html
