name: PyTests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Install ffmpeg / ffprobe
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install project & test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          # NOTE: use a normal install, not editable, because there's no setup.py
          pip install .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
